server:
  port: 7201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hello-service-consumer

# 开启Hystrix
feign:
  hystrix:
    enabled: true