server:
  port: 8761

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://zhongxb:windows8@localhost:8761/eureka/


spring:
  security:
    user:
      name: zhongxb
      password: windows8
      roles: SUPERUSER