eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

zuul:
  routes: # 路由规则
    film: # application.name -> 服务名称 service-id
      path: /film-api/**  # 匹配规则
#    service-id: film

# Hystrix参数配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20 # 超时设置
